import { useRef, useState, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import { useCart } from '@/hooks/useCart'
import { useCurrentUser } from '@/hooks/useCurrentUser'
import { useCheckoutPreview } from '@/hooks/useCheckoutPreview'
import { useCreateOrder } from '@/hooks/useCreateOrder'
import { useRetryPayment } from '@/hooks/useRetryPayment'
import { useUnpaidCheckoutOrder } from '@/hooks/useOrders'
import { useRazorpayCheckout } from '@/features/checkout/useRazorpayCheckout'
import { ShippingForm } from '@/features/checkout/ShippingForm'
import { CheckoutSteps } from '@/features/checkout/CheckoutSteps'
import { CheckoutCartSummary } from '@/features/checkout/CheckoutCartSummary'
import { CouponForm } from '@/features/checkout/CouponForm'
import { PriceBreakdown } from '@/features/checkout/PriceBreakdown'
import { OrderPendingPayment } from '@/features/checkout/OrderPendingPayment'
import { Alert } from '@/components/ui/Alert'
import { ErrorState } from '@/components/ui/ErrorState'
import { Page } from '@/components/ui/Page'
import { Skeleton } from '@/components/ui/Skeleton'
import { PaymentLoadError } from '@/components/ui/PaymentLoadError'
import { getApiErrorMessage } from '@/utils/apiError'
import { normalizeIndianMobile } from '@/utils/phone'
import { Seo } from '@/seo/Seo'
import { orderDetailPath } from '@/constants/routes'
import type { ShippingFormValues } from '@/schemas/checkout.schema'
import type { CheckoutOrderView } from '@/types/checkout'
import type { CheckoutPreviewView } from '@/types/coupons'
import type { UserProfileView } from '@/types/auth'
import { shouldResumeUnpaidOrder } from '@/features/checkout/unpaidCartMatch'
import styles from './CheckoutPage.module.css'

function toCheckoutOrderView(order: OrderDetailView): CheckoutOrderView {
  return {
    id: order.id,
    orderNumber: order.orderNumber,
    status: order.status,
    subtotal: order.subtotal,
    shippingFee: order.shippingFee,
    total: order.total,
    discountAmount: order.discountAmount,
    taxableAmount: order.taxableAmount,
    taxAmount: order.taxAmount,
    taxMode: order.taxMode,
    taxRatePercent: order.taxRatePercent,
    couponCode: order.couponCode,
    currency: order.currency,
    shippingRecipientName: order.shippingRecipientName,
    shippingPhone: order.shippingPhone,
    shippingAddressLine1: order.shippingAddressLine1,
    shippingAddressLine2: order.shippingAddressLine2,
    shippingCity: order.shippingCity,
    shippingState: order.shippingState,
    shippingPostalCode: order.shippingPostalCode,
    shippingCountry: order.shippingCountry,
    items: order.items,
    createdAt: order.createdAt,
  }
}

/** True once the profile carries enough of an address to be worth
 * seeding the form with (UX-07). */
function hasSavedAddress(profile: UserProfileView | undefined): boolean {
  return Boolean(profile?.addressLine1)
}

function savedAddressDefaults(
  profile: UserProfileView | undefined,
): Partial<ShippingFormValues> | undefined {
  if (!hasSavedAddress(profile) || !profile) return undefined
  return {
    shippingPhone: profile.phone ?? '',
    shippingAddressLine1: profile.addressLine1 ?? '',
    shippingAddressLine2: profile.addressLine2 ?? '',
    shippingCity: profile.city ?? '',
    shippingState: profile.state ?? '',
    shippingPostalCode: profile.postalCode ?? '',
    shippingCountry: profile.country ?? '',
  }
}

/**
 * Behind ProtectedRoute (App.tsx). One Idempotency-Key per page mount
 * (§13.G) — every retry of a stuck/failed checkout attempt during this
 * mount reuses it, which is what makes a double-click on "Pay now" safe;
 * a fresh key is only generated by actually remounting this page (e.g.
 * navigating away and back). Lazy useState initializer, not a plain
 * variable, so it survives re-renders without recomputing.
 *
 * UX-06: a server-authoritative price breakdown (subtotal + shipping + tax
 * + total, via the existing read-only POST /checkout/validate) is shown in
 * the summary column *before* payment initiation. If an unpaid order
 * already exists, that order's stored total (including any claimed coupon)
 * is what Razorpay charges — the cart preview is not used in that case.
 * UX-07: the shipping form is seeded from the customer's saved profile
 * address.
 */
export function CheckoutPage() {
  const navigate = useNavigate()
  const [idempotencyKey] = useState(() => crypto.randomUUID())
  const [order, setOrder] = useState<CheckoutOrderView | null>(null)
  const [paymentError, setPaymentError] = useState<string | null>(null)
  const [couponPreview, setCouponPreview] = useState<CheckoutPreviewView | null>(null)
  const [scriptLoadError, setScriptLoadError] = useState<string | null>(null)
  // Guards startPayment against a synchronous double-click. A check against
  // retryPayment.isPending here would NOT work: both clicks of a true
  // zero-latency double-click land on the same pre-re-render closure, so
  // they'd both see the same stale (false) isPending value — the state
  // update from the first click's mutateAsync hasn't committed to a new
  // render yet. A ref mutates synchronously and is shared across every
  // closure holding it, so the second click sees the first click's write
  // immediately, independent of React's render cycle.
  const isRetryingRef = useRef(false)
  const isCreatingRef = useRef(false)

  const { data: cart, isPending: isCartPending, isError: isCartError, error: cartError } = useCart()
  const unpaidQuery = useUnpaidCheckoutOrder()
  // Profile drives Razorpay email/phone prefill AND the shipping-form
  // address prefill. A failure here is non-fatal — the form just starts
  // blank.
  const profileQuery = useCurrentUser()
  const previewQuery = useCheckoutPreview({
    enabled:
      Boolean(cart) &&
      (cart?.items.length ?? 0) > 0 &&
      couponPreview === null &&
      !unpaidQuery.data?.couponCode,
  })
  const createOrder = useCreateOrder()
  const retryPayment = useRetryPayment()

  const { openCheckout, isOpening, isVerifying, isLoadingScript } = useRazorpayCheckout({
    // Never render "payment confirmed" here — only navigate. The
    // confirmation page re-fetches the order and renders strictly off its
    // own status field, which is what stays correct if the webhook
    // disagrees with this call (§13.G).
    onVerified: (result) => void navigate(orderDetailPath(result.orderId), { replace: true }),
    onDismissed: () =>
      setPaymentError(
        'Payment was not completed. Your items are still in the cart — you can retry anytime.',
      ),
    onError: (msg) => {
      if (msg.includes('Failed to load') || msg.includes('Razorpay Checkout script')) {
        setScriptLoadError(msg)
      } else {
        setPaymentError(msg)
      }
    },
  })

  async function startPayment(target: CheckoutOrderView) {
    if (isRetryingRef.current) return
    isRetryingRef.current = true
    setPaymentError(null)
    setScriptLoadError(null)
    try {
      const payment = await retryPayment.mutateAsync(target.id)
      await openCheckout(
        payment,
        { orderNumber: target.orderNumber },
        {
          name: target.shippingRecipientName,
          contact: target.shippingPhone,
          email: profileQuery.data?.email,
        },
      )
    } catch (err) {
      setPaymentError(getApiErrorMessage(err))
    } finally {
      isRetryingRef.current = false
    }
  }

  async function handleSubmitShipping(values: ShippingFormValues) {
    if (isCreatingRef.current) return
    isCreatingRef.current = true
    setPaymentError(null)
    try {
      const created = await createOrder.mutateAsync({
        payload: {
          ...values,
          // The schema already guaranteed this normalises; send the
          // canonical E.164 form (the server re-normalises regardless).
          shippingPhone: normalizeIndianMobile(values.shippingPhone) ?? values.shippingPhone,
          shippingAddressLine2: values.shippingAddressLine2 || undefined,
          couponCode: couponPreview?.couponCode ?? undefined,
        },
        idempotencyKey,
      })
      setOrder(created)
      await startPayment(created)
    } catch {
      // createOrder.isError below renders the message — nothing else to do.
    } finally {
      isCreatingRef.current = false
    }
  }

  const restoredUnpaid =
    !order && unpaidQuery.data && shouldResumeUnpaidOrder(cart, unpaidQuery.data)
      ? toCheckoutOrderView(unpaidQuery.data)
      : null
  const payableOrder = order ?? restoredUnpaid

  function handleRetry() {
    if (payableOrder) {
      void startPayment(payableOrder)
    }
  }

  // Private route — never indexable, in every branch.
  const withSeo = (node: ReactNode): ReactNode => (
    <>
      <Seo title="Checkout" noindex />
      {node}
    </>
  )

  if (isCartPending || profileQuery.isLoading || unpaidQuery.isPending) {
    return withSeo(
      <Page>
        <h1>Checkout</h1>
        <CheckoutSteps current="details" />
        <Skeleton className={styles.skeletonBlock} label="Loading checkout" />
      </Page>,
    )
  }

  if (payableOrder) {
    return withSeo(
      <Page>
        <h1>Checkout</h1>
        <CheckoutSteps current="payment" />
        <OrderPendingPayment
          order={payableOrder}
          error={paymentError}
          onRetry={handleRetry}
          isProcessing={retryPayment.isPending || isOpening || isVerifying}
          isScriptLoading={isLoadingScript}
        />
      </Page>,
    )
  }

  if (isCartError) {
    return withSeo(
      <Page>
        <ErrorState title="Checkout" message={getApiErrorMessage(cartError)} />
      </Page>,
    )
  }

  if (cart.items.length === 0) {
    return withSeo(
      <Page>
        <h1>Checkout</h1>
        <Alert variant="info">Your cart is empty — add something before checking out.</Alert>
      </Page>,
    )
  }

  const hasUnavailableItems = cart.items.some((item) => !item.isAvailable)
  if (hasUnavailableItems) {
    return withSeo(
      <Page>
        <h1>Checkout</h1>
        <Alert variant="error">
          Remove the unavailable item(s) in your cart before checking out.
        </Alert>
      </Page>,
    )
  }

  // Coupon preview drives the breakdown until Pay now. If an unpaid order
  // already exists without a coupon, submitting with a code attaches it
  // to that order so Razorpay charges the discounted total.
  const effectivePreview = couponPreview ?? previewQuery.data ?? null
  const savedAddress = savedAddressDefaults(profileQuery.data)

  return withSeo(
    <Page>
      <h1>Checkout</h1>
      <CheckoutSteps current="details" />
      {scriptLoadError && <PaymentLoadError message={scriptLoadError} onRetry={() => setScriptLoadError(null)} />}
      <div className={styles.layout}>
        <div className={styles.formColumn}>
          <h2 className={styles.sectionHeading}>Delivery details</h2>
          {createOrder.isError && <Alert variant="error">{getApiErrorMessage(createOrder.error)}</Alert>}
          <ShippingForm
            onSubmit={(values) => void handleSubmitShipping(values)}
            isSubmitting={createOrder.isPending || retryPayment.isPending || isOpening}
            isScriptLoading={isLoadingScript}
            defaultValues={savedAddress}
            prefilled={Boolean(savedAddress)}
          />
        </div>
        <aside className={styles.summaryColumn} aria-label="Order summary and payment">
          <CheckoutCartSummary cart={cart} />
          <CouponForm appliedPreview={couponPreview} onApplied={setCouponPreview} />
          {effectivePreview && (
            <div className={styles.breakdown}>
              <h2 className={styles.sectionHeading}>Order total</h2>
              <PriceBreakdown
                subtotal={effectivePreview.subtotal}
                shippingFee={effectivePreview.shippingFee}
                discountAmount={effectivePreview.discountAmount}
                couponCode={effectivePreview.couponCode}
                taxAmount={effectivePreview.taxAmount}
                taxMode={effectivePreview.taxMode}
                total={effectivePreview.total}
              />
              <p className={styles.breakdownNote}>
                Final amounts are re-confirmed when you place the order.
              </p>
            </div>
          )}
        </aside>
      </div>
    </Page>,
  )
}
