export interface CategoryShowcaseCard {
  id: string
  title: string
  image: string
  salePrice: string
  originalPrice: string
  discount: string
  tag: string
  rating: string
  reviews: number
  categorySlug: string
  features: string[]
}

export interface CoreCategoryData {
  key: string
  title: string
  eyebrow: string
  subtitle: string
  bannerImg: string
  bannerAlt: string
  badgeText: string
  featureChips: { label: string; query: string; badge?: string }[]
  cards: CategoryShowcaseCard[]
}

export const CORE_CATEGORIES_MAP: Record<string, CoreCategoryData> = {
  'business-cards': {
    key: 'business-cards',
    title: 'Business Cards',
    eyebrow: 'Executive Stationery & Brand Identity',
    subtitle:
      'Custom Premium 3D embossed cards, Blue Gold executive stationery, and Modern Navy Blue corporate cards crafted on heavy 350+ GSM cardstock.',
    bannerImg: '/images/products/store/bcard-blue-gold-premium.jpg',
    bannerAlt: 'Executive Business Cards and Premium Corporate Stationery',
    badgeText: 'From ₹399.00',
    featureChips: [
      { label: 'All Business Cards', query: 'business-cards' },
      { label: 'Custom Premium 3D', query: '3d', badge: 'Popular' },
      { label: 'Blue Gold Foil', query: 'gold', badge: 'Luxury' },
      { label: 'Modern Navy Blue', query: 'navy', badge: 'Trending' },
      { label: 'Matte Lamination', query: 'matte' },
      { label: 'Spot UV Coating', query: 'uv' },
    ],
    cards: [
      {
        id: 'bc-1',
        title: 'Custom Premium 3D Business Cards',
        image: '/images/products/store/bcard-custom-3d-navy.jpg',
        salePrice: '₹399.00',
        originalPrice: '₹599.00',
        discount: '33% OFF',
        tag: 'Bestseller',
        rating: '5.0',
        reviews: 98,
        categorySlug: 'business-cards',
        features: ['350 GSM Cardstock', 'Raised 3D Spot UV Finish', 'Sharp Edge-to-Edge Cut'],
      },
      {
        id: 'bc-2',
        title: 'Premium Blue Gold Business Cards',
        image: '/images/products/store/bcard-blue-gold-premium.jpg',
        salePrice: '₹399.00',
        originalPrice: '₹599.00',
        discount: '33% OFF',
        tag: 'Luxury',
        rating: '4.95',
        reviews: 86,
        categorySlug: 'business-cards',
        features: ['Metallic Gold Accent Swoosh', 'Velvet Smooth Touch', 'Dual-Sided Executive Layout'],
      },
      {
        id: 'bc-3',
        title: 'Modern Navy Blue Business Cards',
        image: '/images/products/store/bcard-modern-navy-blue.jpg',
        salePrice: '₹399.00',
        originalPrice: '₹599.00',
        discount: '33% OFF',
        tag: 'Trending',
        rating: '4.9',
        reviews: 74,
        categorySlug: 'business-cards',
        features: ['Deep Navy Color Palette', 'Anti-Glare Matte Finish', 'Executive Presentation'],
      },
    ],
  },
  logo: {
    key: 'logo',
    title: 'Logo',
    eyebrow: 'Illuminated Wall Signs & Multi-Size Artwork',
    subtitle:
      'High-lumen LED acrylic wall signs for iPhone, Realme, Samsung, and multi-size sunflower prints engineered for standout presence.',
    bannerImg: '/images/products/store/logo-iphone-led-sign.jpg',
    bannerAlt: 'Illuminated LED Logo Wall Signs and Custom Branding Signs',
    badgeText: 'From ₹100.00',
    featureChips: [
      { label: 'All Logo Signs', query: 'logo' },
      { label: 'iPhone LED Sign', query: 'iphone', badge: 'Hot' },
      { label: 'Realme LED Sign', query: 'realme', badge: 'Trending' },
      { label: 'Samsung LED Sign', query: 'samsung', badge: 'Popular' },
      { label: 'New Logo Art Prints', query: 'new-logo', badge: 'From ₹100' },
    ],
    cards: [
      {
        id: 'logo-1',
        title: 'New logo',
        image: '/images/products/store/logo-sunflower-new.jpg',
        salePrice: 'From ₹100.00',
        originalPrice: '₹200.00',
        discount: '50% OFF',
        tag: 'Multi-Size',
        rating: '5.0',
        reviews: 42,
        categorySlug: 'logo',
        features: ['Available in 4x5, 10x10, 50x50', 'High Definition Vibrant Print', 'Custom Artwork Integration'],
      },
      {
        id: 'logo-2',
        title: 'iPhone LED Logo Wall Sign',
        image: '/images/products/store/logo-iphone-led-sign.jpg',
        salePrice: '₹799.00',
        originalPrice: '₹1,299.00',
        discount: '38% OFF',
        tag: 'Bestseller',
        rating: '5.0',
        reviews: 64,
        categorySlug: 'logo',
        features: ['Backlit Illuminated LED', 'Laser-Cut Acrylic Finish', 'Wall Mount Ready Kit'],
      },
      {
        id: 'logo-3',
        title: 'Realme LED Logo Wall Sign',
        image: '/images/products/store/logo-realme-led-sign.jpg',
        salePrice: '₹799.00',
        originalPrice: '₹1,299.00',
        discount: '38% OFF',
        tag: 'Trending',
        rating: '4.95',
        reviews: 58,
        categorySlug: 'logo',
        features: ['Vivid Neon Yellow Glow', 'Storefront Commercial Signage', 'Energy Efficient LEDs'],
      },
      {
        id: 'logo-4',
        title: 'Samsung LED Logo Wall Sign',
        image: '/images/products/store/logo-samsung-led-sign.jpg',
        salePrice: '₹799.00',
        originalPrice: '₹1,299.00',
        discount: '38% OFF',
        tag: 'Popular',
        rating: '4.9',
        reviews: 51,
        categorySlug: 'logo',
        features: ['Royal Blue High-Lumen LED', 'Weatherproof Acrylic Backing', 'Easy Plug & Play Adapter'],
      },
    ],
  },
  mugs: {
    key: 'mugs',
    title: 'Mugs',
    eyebrow: 'Personalized Photo & Heart Handle Keepsakes',
    subtitle:
      'Classic photo memory mugs, romantic heart collages, heat-revealing magic cups, and sculpted heart handle drinkware.',
    bannerImg: '/images/products/store/mug-classic-photo-memory.jpg',
    bannerAlt: 'Personalized Photo Mugs and Heart Handle Drinkware',
    badgeText: 'All ₹299.00',
    featureChips: [
      { label: 'All Mugs', query: 'mugs' },
      { label: 'Classic Memory Mug', query: 'classic', badge: 'Popular' },
      { label: 'Couple Heart Collage', query: 'collage', badge: 'Romantic' },
      { label: 'Love Hearts Mug', query: 'hearts' },
      { label: 'Heart Handle Mug', query: 'heart-handle', badge: 'Hot' },
      { label: 'Magic Photo Reveal', query: 'magic', badge: 'Trending' },
    ],
    cards: [
      {
        id: 'mug-1',
        title: 'Classic Photo Memory Mug',
        image: '/images/products/store/mug-classic-photo-memory.jpg',
        salePrice: '₹299.00',
        originalPrice: '₹499.00',
        discount: '40% OFF',
        tag: 'Bestseller',
        rating: '4.9',
        reviews: 118,
        categorySlug: 'mugs',
        features: ['Ocean Blue Inner & Handle', 'HD Edge-to-Edge Sublimation', 'Microwave & Dishwasher Safe'],
      },
      {
        id: 'mug-2',
        title: 'Couple Heart Collage Mug',
        image: '/images/products/store/mug-couple-heart-collage.jpg',
        salePrice: '₹299.00',
        originalPrice: '₹499.00',
        discount: '40% OFF',
        tag: 'Romantic',
        rating: '4.95',
        reviews: 87,
        categorySlug: 'mugs',
        features: ['Heart Photo Collage Frame', 'Ribbon Anniversary Theme', 'Black Contrast Rim & Handle'],
      },
      {
        id: 'mug-3',
        title: 'Love Hearts Photo Mug',
        image: '/images/products/store/mug-love-hearts.jpg',
        salePrice: '₹299.00',
        originalPrice: '₹499.00',
        discount: '40% OFF',
        tag: 'Most Loved',
        rating: '4.85',
        reviews: 64,
        categorySlug: 'mugs',
        features: ['Pink Ombre Hearts Pattern', '"Spread Your Love" Personalization', 'Glossy Ceramic Finish'],
      },
      {
        id: 'mug-4',
        title: 'Heart Handle Personalized Photo Mug',
        image: '/images/products/store/mug-heart-handle-steaming.jpg',
        salePrice: '₹299.00',
        originalPrice: '₹499.00',
        discount: '40% OFF',
        tag: 'Special Handle',
        rating: '4.92',
        reviews: 73,
        categorySlug: 'mugs',
        features: ['Sculpted Ceramic Heart Handle', '330ml Generous Volume', 'High-Gloss White Glaze'],
      },
      {
        id: 'mug-5',
        title: 'Personalized Couple Photo Magic Mug',
        image: '/images/products/store/mug-personalized-magic-reveal.jpg',
        salePrice: '₹299.00',
        originalPrice: '₹499.00',
        discount: '40% OFF',
        tag: 'Magic Reveal',
        rating: '5.0',
        reviews: 96,
        categorySlug: 'mugs',
        features: ['Heat-Activated Reveal Mechanism', 'Black Cold to Full Photo Warm', 'Mesmerizing Surprise Gift'],
      },
      {
        id: 'mug-6',
        title: 'Heart Handle Photo Mug (Black Cutout)',
        image: '/images/products/store/mug-heart-handle-cutout.jpg',
        salePrice: '₹299.00',
        originalPrice: '₹499.00',
        discount: '40% OFF',
        tag: 'Trending',
        rating: '4.88',
        reviews: 55,
        categorySlug: 'mugs',
        features: ['Matte Black Exterior with Heart Cutout', 'Vibrant Portrait Display', 'Durable Stone Ceramic'],
      },
    ],
  },
  'name-plates': {
    key: 'name-plates',
    title: 'Name Plates',
    eyebrow: 'Backlit LED Villa & Flat Door Plaques',
    subtitle:
      'Warm golden LED backlit plaques, decorative peacock feather flat number plates, and ornate luxury family nameplates.',
    bannerImg: '/images/products/store/nameplate-mukund-villa.jpg',
    bannerAlt: 'Mukund Villa LED Name Plates and Decorative Flat Number Plates',
    badgeText: 'From ₹99.00',
    featureChips: [
      { label: 'All Name Plates', query: 'name-plates' },
      { label: 'Mukund Villa LED', query: 'mukund', badge: 'Customizable' },
      { label: 'Flat Number Plate', query: 'flat', badge: 'Bestseller' },
      { label: 'Premium Mehta Plate', query: 'mehta', badge: '₹99.00' },
      { label: 'Acrylic LED Entrance', query: 'led' },
    ],
    cards: [
      {
        id: 'np-1',
        title: 'Mukund Villa Premium LED Name Plate',
        image: '/images/products/store/nameplate-mukund-villa.jpg',
        salePrice: '₹999.00',
        originalPrice: '₹1,599.00',
        discount: '38% OFF',
        tag: 'Customizable',
        rating: '5.0',
        reviews: 86,
        categorySlug: 'name-plates',
        features: ['Warm Golden Backlight', 'Laser-Etched Devnagari & English Calligraphy', 'Weatherproof IP65 Adapter'],
      },
      {
        id: 'np-2',
        title: 'Decorative Flat Number Name Plate',
        image: '/images/products/store/nameplate-flat-104.jpg',
        salePrice: '₹999.00',
        originalPrice: '₹1,499.00',
        discount: '33% OFF',
        tag: 'Bestseller',
        rating: '4.95',
        reviews: 62,
        categorySlug: 'name-plates',
        features: ['Peacock Feather Golden Motifs', 'Apartment & Flat Door Plaque', 'Glowing Edge Acrylic'],
      },
      {
        id: 'np-3',
        title: 'Premium Name Plate',
        image: '/images/products/store/nameplate-mehta-glowing.jpg',
        salePrice: '₹99.00',
        originalPrice: '₹199.00',
        discount: '50% OFF',
        tag: 'Special Offer',
        rating: '4.9',
        reviews: 48,
        categorySlug: 'name-plates',
        features: ['Ornate Backlit Jali Border', 'Laser Cut Surname Typography', 'Durable Acrylic Face'],
      },
    ],
  },
  't-shirts': {
    key: 't-shirts',
    title: 'T-Shirts',
    eyebrow: 'Graphic Vintage, Streetwear & Everyday Apparel',
    subtitle:
      'Originals 1990 vintage graphic tees, My Daily Dose coffee tees, and vibrant Hustle graffiti streetwear printed on pure combed cotton.',
    bannerImg: '/images/products/store/tshirt-hustle-graffiti.jpg',
    bannerAlt: 'Originals 1990, My Daily Dose, and Hustle Graffiti Graphic T-Shirts',
    badgeText: 'All ₹499.00',
    featureChips: [
      { label: 'All T-Shirts', query: 't-shirts' },
      { label: 'Originals 1990 Graphic', query: '1990', badge: 'Bestseller' },
      { label: 'My Daily Dose Coffee', query: 'daily-dose', badge: 'Trending' },
      { label: 'Hustle Graffiti Streetwear', query: 'hustle', badge: 'Hot' },
      { label: '100% Combed Cotton', query: 'cotton' },
    ],
    cards: [
      {
        id: 'ts-1',
        title: 'Originals 1990 Graphic T-Shirt',
        image: '/images/products/store/tshirt-originals-1990.jpg',
        salePrice: '₹499.00',
        originalPrice: '₹799.00',
        discount: '38% OFF',
        tag: 'Bestseller',
        rating: '4.95',
        reviews: 142,
        categorySlug: 't-shirts',
        features: ['100% Combed Cotton', 'Vintage 1990 Typography', 'Bio-Washed Pre-Shrunk'],
      },
      {
        id: 'ts-2',
        title: 'My Daily Dose Graphic T-Shirt',
        image: '/images/products/store/tshirt-daily-dose.jpg',
        salePrice: '₹499.00',
        originalPrice: '₹799.00',
        discount: '38% OFF',
        tag: 'Trending',
        rating: '4.9',
        reviews: 95,
        categorySlug: 't-shirts',
        features: ['Coffee Lover Illustration', 'Breathable Round Neck Fit', 'Fade-Proof Screen Print'],
      },
      {
        id: 'ts-3',
        title: 'Hustle Graffiti Graphic T-Shirt',
        image: '/images/products/store/tshirt-hustle-graffiti.jpg',
        salePrice: '₹499.00',
        originalPrice: '₹799.00',
        discount: '38% OFF',
        tag: 'Streetwear',
        rating: '5.0',
        reviews: 110,
        categorySlug: 't-shirts',
        features: ['Mustard Streetwear Drop-Shoulder', 'Urban Skull Graffiti Art', 'Heavy 220 GSM Cotton'],
      },
    ],
  },
  all: {
    key: 'all',
    title: 'All products',
    eyebrow: 'Complete Studio Catalogue',
    subtitle:
      'Explore our full collection of verified store merchandise — LED nameplates, graphic t-shirts, illuminated logo wall signs, ceramic mugs, and custom business cards.',
    bannerImg: '/images/products/store/nameplate-mukund-villa.jpg',
    bannerAlt: 'PrintForge Store Catalog Products',
    badgeText: 'Verified Store Products',
    featureChips: [
      { label: 'All Products', query: '' },
      { label: 'Business Cards', query: 'business-cards', badge: '₹399.00' },
      { label: 'Logo & Signs', query: 'logo', badge: 'From ₹100' },
      { label: 'Mugs', query: 'mugs', badge: '₹299.00' },
      { label: 'Name Plates', query: 'name-plates', badge: 'Customizable' },
      { label: 'T-Shirts', query: 't-shirts', badge: '₹499.00' },
    ],
    cards: [
      {
        id: 'all-np-mukund',
        title: 'Mukund Villa Premium LED Name Plate',
        image: '/images/products/store/nameplate-mukund-villa.jpg',
        salePrice: '₹999.00',
        originalPrice: '₹1,599.00',
        discount: '38% OFF',
        tag: 'Customizable',
        rating: '5.0',
        reviews: 86,
        categorySlug: 'name-plates',
        features: ['Warm Golden Backlight', 'Laser-Cut Devnagari Script', 'IP65 Weatherproof'],
      },
      {
        id: 'all-ts-1990',
        title: 'Originals 1990 Graphic T-Shirt',
        image: '/images/products/store/tshirt-originals-1990.jpg',
        salePrice: '₹499.00',
        originalPrice: '₹799.00',
        discount: '38% OFF',
        tag: 'Bestseller',
        rating: '4.95',
        reviews: 142,
        categorySlug: 't-shirts',
        features: ['100% Combed Cotton', 'Vintage 1990 Print', 'Pre-Shrunk Comfort'],
      },
      {
        id: 'all-bc-3d',
        title: 'Custom Premium 3D Business Cards',
        image: '/images/products/store/bcard-custom-3d-navy.jpg',
        salePrice: '₹399.00',
        originalPrice: '₹599.00',
        discount: '33% OFF',
        tag: 'Hotselling',
        rating: '5.0',
        reviews: 98,
        categorySlug: 'business-cards',
        features: ['350 GSM Cardstock', 'Raised 3D Spot UV', 'Sharp Edges'],
      },
      {
        id: 'all-logo-iphone',
        title: 'iPhone LED Logo Wall Sign',
        image: '/images/products/store/logo-iphone-led-sign.jpg',
        salePrice: '₹799.00',
        originalPrice: '₹1,299.00',
        discount: '38% OFF',
        tag: 'Premium',
        rating: '5.0',
        reviews: 64,
        categorySlug: 'logo',
        features: ['Backlit Illuminated LED', 'Laser-Cut Acrylic', 'Wall Mount Ready'],
      },
      {
        id: 'all-mug-classic',
        title: 'Classic Photo Memory Mug',
        image: '/images/products/store/mug-classic-photo-memory.jpg',
        salePrice: '₹299.00',
        originalPrice: '₹499.00',
        discount: '40% OFF',
        tag: 'Most Loved',
        rating: '4.9',
        reviews: 118,
        categorySlug: 'mugs',
        features: ['Blue Accent Handle', 'Edge-to-Edge Print', 'Microwave Safe'],
      },
      {
        id: 'all-ts-hustle',
        title: 'Hustle Graffiti Graphic T-Shirt',
        image: '/images/products/store/tshirt-hustle-graffiti.jpg',
        salePrice: '₹499.00',
        originalPrice: '₹799.00',
        discount: '38% OFF',
        tag: 'Streetwear',
        rating: '5.0',
        reviews: 110,
        categorySlug: 't-shirts',
        features: ['Mustard Streetwear', 'Graffiti Art', '220 GSM Cotton'],
      },
      {
        id: 'all-np-flat104',
        title: 'Decorative Flat Number Name Plate',
        image: '/images/products/store/nameplate-flat-104.jpg',
        salePrice: '₹999.00',
        originalPrice: '₹1,499.00',
        discount: '33% OFF',
        tag: 'Popular',
        rating: '4.95',
        reviews: 62,
        categorySlug: 'name-plates',
        features: ['Golden Peacock Feather', 'Apartment Flat Plaque', 'Glowing Acrylic'],
      },
      {
        id: 'all-logo-realme',
        title: 'Realme LED Logo Wall Sign',
        image: '/images/products/store/logo-realme-led-sign.jpg',
        salePrice: '₹799.00',
        originalPrice: '₹1,299.00',
        discount: '38% OFF',
        tag: 'Trending',
        rating: '4.95',
        reviews: 58,
        categorySlug: 'logo',
        features: ['Neon Yellow Glow', 'Storefront Commercial Sign', 'Plug & Play'],
      },
      {
        id: 'all-bc-gold',
        title: 'Premium Blue Gold Business Cards',
        image: '/images/products/store/bcard-blue-gold-premium.jpg',
        salePrice: '₹399.00',
        originalPrice: '₹599.00',
        discount: '33% OFF',
        tag: 'Luxury',
        rating: '4.95',
        reviews: 86,
        categorySlug: 'business-cards',
        features: ['Metallic Gold Accent', 'Velvet Smooth Base', 'Dual-Sided Print'],
      },
      {
        id: 'all-mug-magic',
        title: 'Personalized Couple Photo Magic Mug',
        image: '/images/products/store/mug-personalized-magic-reveal.jpg',
        salePrice: '₹299.00',
        originalPrice: '₹499.00',
        discount: '40% OFF',
        tag: 'Magic Reveal',
        rating: '5.0',
        reviews: 96,
        categorySlug: 'mugs',
        features: ['Heat Activated Reveal', 'Cold Black to Full Picture', 'Great Gift'],
      },
      {
        id: 'all-logo-new',
        title: 'New logo',
        image: '/images/products/store/logo-sunflower-new.jpg',
        salePrice: 'From ₹100.00',
        originalPrice: '₹200.00',
        discount: '50% OFF',
        tag: 'Multi-Size',
        rating: '5.0',
        reviews: 42,
        categorySlug: 'logo',
        features: ['Sizes 4x5, 10x10, 50x50', 'High Definition Print', 'Vibrant Flowers'],
      },
      {
        id: 'all-ts-daily',
        title: 'My Daily Dose Graphic T-Shirt',
        image: '/images/products/store/tshirt-daily-dose.jpg',
        salePrice: '₹499.00',
        originalPrice: '₹799.00',
        discount: '38% OFF',
        tag: 'Trending',
        rating: '4.9',
        reviews: 95,
        categorySlug: 't-shirts',
        features: ['Coffee Lover Graphic', 'Round Neck Fit', 'Fade-Proof Print'],
      },
      {
        id: 'all-bc-navy',
        title: 'Modern Navy Blue Business Cards',
        image: '/images/products/store/bcard-modern-navy-blue.jpg',
        salePrice: '₹399.00',
        originalPrice: '₹599.00',
        discount: '33% OFF',
        tag: 'Executive',
        rating: '4.9',
        reviews: 74,
        categorySlug: 'business-cards',
        features: ['Matte Laminated Navy', 'Clean Corporate Layout', 'Sharp Typography'],
      },
      {
        id: 'all-logo-samsung',
        title: 'Samsung LED Logo Wall Sign',
        image: '/images/products/store/logo-samsung-led-sign.jpg',
        salePrice: '₹799.00',
        originalPrice: '₹1,299.00',
        discount: '38% OFF',
        tag: 'Commercial',
        rating: '4.9',
        reviews: 51,
        categorySlug: 'logo',
        features: ['Royal Blue LED', 'Illuminated Acrylic', 'Durable Enclosure'],
      },
      {
        id: 'all-mug-collage',
        title: 'Couple Heart Collage Mug',
        image: '/images/products/store/mug-couple-heart-collage.jpg',
        salePrice: '₹299.00',
        originalPrice: '₹499.00',
        discount: '40% OFF',
        tag: 'Romantic',
        rating: '4.95',
        reviews: 87,
        categorySlug: 'mugs',
        features: ['Heart Photo Collage', 'Ribbon Anniversary Border', 'Black Handle'],
      },
      {
        id: 'all-np-mehta',
        title: 'Premium Name Plate',
        image: '/images/products/store/nameplate-mehta-glowing.jpg',
        salePrice: '₹99.00',
        originalPrice: '₹199.00',
        discount: '50% OFF',
        tag: 'Special Offer',
        rating: '4.9',
        reviews: 48,
        categorySlug: 'name-plates',
        features: ['Ornate Backlit Jali', 'Laser Cut Surname', 'Acrylic Build'],
      },
    ],
  },
}

/**
 * Resolves the active core category given query parameters.
 */
export function resolveCoreCategory(
  categoryParam?: string | null,
  searchParam?: string | null,
  activeCatName?: string | null,
): CoreCategoryData {
  const term = (categoryParam || searchParam || activeCatName || '').toLowerCase().trim()

  if (term.includes('business') || term.includes('card')) {
    return CORE_CATEGORIES_MAP['business-cards']
  }
  if (term.includes('logo') || term.includes('sign')) {
    return CORE_CATEGORIES_MAP['logo']
  }
  if (term.includes('mug') || term.includes('cup') || term.includes('drinkware')) {
    return CORE_CATEGORIES_MAP['mugs']
  }
  if (term.includes('name') || term.includes('plat') || term.includes('plaque')) {
    return CORE_CATEGORIES_MAP['name-plates']
  }
  if (
    term.includes('t-shirt') ||
    term.includes('tshirt') ||
    term.includes('shirt') ||
    term.includes('apparel') ||
    term.includes('polo')
  ) {
    return CORE_CATEGORIES_MAP['t-shirts']
  }

  return CORE_CATEGORIES_MAP['all']
}
